# Generated by Django 5.0.14 on 2026-09-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Social share image (1200x630). Used for Open Graph and Twitter cards.', null=True, upload_to='seo/'),
        ),
    ]
