# Generated by Django 5.0.14 on 2026-09-03 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, default='', max_length=300)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('release_date', models.DateField()),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux'), ('android', 'Android'), ('ios', 'iOS'), ('cross_platform', 'Cross Platform'), ('web', 'Web'), ('other', 'Other')], default='windows', max_length=20)),
                ('architecture', models.CharField(choices=[('x86', 'x86'), ('x64', 'x64'), ('arm', 'ARM'), ('arm64', 'ARM64'), ('universal', 'Universal')], default='x64', max_length=20)),
                ('file', models.FileField(upload_to='software/')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('features', models.TextField(blank=True, default='', help_text='One feature per line')),
                ('requirements', models.TextField(blank=True, default='')),
                ('installation', models.TextField(blank=True, default='')),
                ('changelog', models.TextField(blank=True, default='')),
                ('source_url', models.URLField(blank=True, default='')),
                ('website_url', models.URLField(blank=True, default='')),
                ('license', models.CharField(blank=True, default='Proprietary', max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Software',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='software/screenshots/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='software.software')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
