# Generated by Django 5.0.14 on 2026-09-03 12:00

import software.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='file',
            field=models.FileField(upload_to='software/', validators=[software.models.validate_software_file]),
        ),
    ]
